$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsiveClass:true,
    loop:true,
    center:true,
    autoplay:true,
    autoplayTimeout:8000,
    info:true,
    responsive:{
        0:{
            items:1
        },
        900:{
            items:2
        },
        1100:{
            items:3
        },
        1200:{
            items:3
        }
    }
})