$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsiveClass:true,
    autoplay:true,
    autoplayTimeout:4000,
    info:true,
    responsive:{
        0:{
            items:1
        },
        900:{
            items:2
        },
        1000:{
            items:3
        }
    }
})