$('.owl-carousel').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    responsiveClass:true,
    loop:true,
    autoplay:true,
    autoplayTimeout:8000,
    responsive:{
        0:{
            items:1
        },
        900:{
            items:2
        },
        1100:{
            items:2
        },
        1400:{
            items:3
        },
        1600:{
            items:4
        }
    }
})